### ISSUE TITLE
can't broke the wall in iPhone5s(ios8.4) and iPhone6(8.4).

### ISSUE THREAD

**Issue by weqeo** [tuoxie007/Shadowsocks-iOS-Demo#2]
can't broke the wall in iPhone5s(ios8.4) and iPhone6(8.4).
read error like this:
bind failed, Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use" UserInfo=0x174074c80 {NSLocalizedDescription=Address already in use, NSLocalizedFailureReason=Error in bind() function}

**Comment by tuoxie007** [comment]
Change another local port

**Comment by weqeo** [comment]
It works， thinks ！

**Comment by weqeo** [comment]
It works， thanks ！
